[package]
name = "rminer"
version = "0.1.0"
authors = ["Jan Čapek <jan@braiins.com>"]
edition = '2018'

[workspace]

members = [
    "s9-io",
    "antminer-dev",
]

[dependencies]
s9-io = { path = "s9-io" }
libc = "0.2.43"
memmap = "0.6.2"
nix = "0.11.0"
bitfield = "0.13.0"
bitflags="1.0.3"
packed_struct="0.3"
packed_struct_codegen = "0.3"
uint = "0.5.0"
byteorder = "1.2.7"
linux-embedded-hal = "0.2.0"
sysfs_gpio = "0.5.3"
lazy_static = "1.2"
slog = { version = "~2.4", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4"
slog-async = "2.3"
failure = "0.1.5"
uio = { version = "0.2", path = "uio" }
futures-locks = "0.3.3"
futures = "0.1.26"
tokio-async-await = "0.1.7"
tokio = { version = "0.1.19", features = ["async-await-preview"] }
bitcoin_hashes = "0.3.2"
downcast-rs = "1.0.4"

[dependencies.embedded-hal]
version = "0.2.0"
# Temporary for InputPin and OutputPin traits
features = ["unproven"]

[features]
default = []
hctl_polling = []
