# bOSminer configuration

# This option tells bosminer that we are using "alpha" version of config
# file format. It's mandatory.
config_version = "alpha"

asic_boost = true

# Frequency and voltage are set for all chains
frequency = 650
voltage = 9

# Override frequency and voltage for chain 8
#[chain.8]
#frequency = 560
#voltage = 8.9

# Override voltage for chain 7
#[chain.7]
#voltage = 8.8

# Configuration of temperature control
#
# If you want to disable temperature control, then comment-out the following
# section.
[temperature]
dangerous_temp = 105.0
hot_temp = 95.0

# Configuration of fans
#
# If you want to disable fan control completely, then comment-out this section.
[fans]
# You can either control fans with target temperature (in Celsius):
temperature = 75
# Or you can set fixed fan speed (in %):
#speed = 70
# but these two options are mutually exclusive.

# Set this to minimum number of fans required for bOSminer to run
min_fans = 1

# Declares pools. This section can be repeated.
#[[pool]]
#url = "v2.stratum.slushpool.com:3336"
#user = "!non-existent-user!"
