build:
    # name of subdirectory in the build directory
    name: devel
    # file with default LEDE configuration
    config: defaults/devel.conf
    # always copy default configuration file
    config_always: no
    # relative or absolute path to the build directory
    dir: build
    # specifies the number of jobs to run simultaneously
    jobs: 4
    # show all commands during build process
    debug: no
    # path to Xilinx SDK
    xilinx_sdk: ~/opt/xilinx/SDK/2017.2

remote:
    # default branch for repositories
    branch: braiins
    # always fetch latest source code
    fetch: no

    # list of remote repositories
    repos:
        lede:
            uri: git@gitlab.bo:x/lede.git
        luci:
            uri: git@gitlab.bo:x/luci.git
        linux:
            uri: git@gitlab.bo:x/linux-xlnx.git
        cgminer:
            uri: git@gitlab.bo:x/cgminer.git
            branch: braiins-old-spi

feeds:
    # always create feeds.conf
    create_always: no
    # always update feeds
    update_always: no
    # always install feeds
    install_always: no
