[package]
name = "bosminer"
version = "0.1.0"
authors = ["Braiins <braiins@braiins.com>"]
license = "GPL-3.0-or-later"
edition = '2018'

[dependencies]
ii-async-compat = { path = "../../utils-rs/async-compat" }
ii-bitcoin = { path = "../../coins/bitcoin" }
ii-logging = { path = "../../utils-rs/logging" }
ii-stratum = { path = "../../protocols/stratum" }
ii-wire = { path = "../../protocols/wire" }
failure = "0.1.5"
lazy_static = "1.3"
tokio = { version = "=0.1.19", features = ["async-await-preview"] }
tokio-threadpool = "0.1.14"
futures-preview = { version = "=0.3.0-alpha.16", features = ["compat"] }
futures-01 = { version = "0.1.27", package = "futures" }
downcast-rs = "1.0.4"
clap = "2.33.0"
hex = "0.3.1"
